# Generated by Django 4.0 on 2022-01-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Date_Asked',
            new_name='date_posted',
        ),
    ]
