# Generated by Django 4.0 on 2022-01-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_date_asked_question_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Date_Answered',
            new_name='date_posted',
        ),
    ]
