# Generated by Django 4.0 on 2022-01-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rename_date_answered_answer_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
