# Generated by Django 4.0 on 2022-01-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_answervote'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
